"""Render a SmartDNS configuration from the opt-in DNS policy."""

import ipaddress
import re
import tomllib

from .config import ConfigError, _resolve_path
from .dns_profile import load_dns_profile

_SMARTDNS_KEYS = {
    "listen",
    "domestic_domain_set",
    "cache_file",
    "cache_size",
    "bootstrap_servers",
    "speed_ports",
}
_SAFE_PATH = re.compile(r"^/[A-Za-z0-9_./-]+$")


def _absolute_path(settings, key):
    value = settings.get(key)
    if not isinstance(value, str) or not _SAFE_PATH.fullmatch(value) or ".." in value.split("/"):
        raise ConfigError(f"smartdns.{key} must be an absolute path without spaces or controls")
    return value


def _listen(value):
    if not isinstance(value, str):
        raise ConfigError("smartdns.listen must be an IPv4 address and port")
    host, separator, port_text = value.rpartition(":")
    try:
        ipaddress.IPv4Address(host)
        port = int(port_text)
    except ValueError as e:
        raise ConfigError("smartdns.listen must be an IPv4 address and port") from e
    if not separator or not port_text.isdigit() or not 0 < port < 65536:
        raise ConfigError("smartdns.listen must be an IPv4 address and port")
    return value


def _positive_int(value, key, maximum=None):
    if (
        isinstance(value, bool)
        or not isinstance(value, int)
        or value <= 0
        or (maximum is not None and value > maximum)
    ):
        raise ConfigError(f"smartdns.{key} must contain valid positive integers")
    return value


def load_smartdns_profile(path=None):
    """Read the shared DNS policy and validate SmartDNS-specific settings."""
    dns = load_dns_profile(path)
    resolved = _resolve_path(path)
    if not resolved:
        raise ConfigError("No config file found for SmartDNS rendering")
    with open(resolved, "rb") as stream:
        settings = tomllib.load(stream).get("smartdns")
    if not isinstance(settings, dict):
        raise ConfigError("Add a [smartdns] table to config.toml before rendering")
    unknown = set(settings) - _SMARTDNS_KEYS
    if unknown:
        raise ConfigError(f"Unknown [smartdns] key: {sorted(unknown)[0]}")

    listen = _listen(settings.get("listen", "127.0.0.1:6053"))
    domain_set = _absolute_path(settings, "domestic_domain_set")
    cache_file = _absolute_path(settings, "cache_file")
    cache_size = _positive_int(settings.get("cache_size", 32768), "cache_size")
    bootstrap = settings.get("bootstrap_servers", ["223.5.5.5", "1.1.1.1"])
    if not isinstance(bootstrap, list) or not bootstrap:
        raise ConfigError("smartdns.bootstrap_servers must list IPv4 addresses")
    try:
        if any(not isinstance(value, str) for value in bootstrap):
            raise ValueError("non-string")
        bootstrap = [str(ipaddress.IPv4Address(value)) for value in bootstrap]
    except ValueError as e:
        raise ConfigError("smartdns.bootstrap_servers must list IPv4 addresses") from e

    ports = settings.get("speed_ports", [443, 80])
    if not isinstance(ports, list) or not ports:
        raise ConfigError("smartdns.speed_ports must list TCP ports")
    ports = [_positive_int(port, "speed_ports", maximum=65535) for port in ports]

    for upstream in dns["domestic_upstreams"]:
        if "://" not in upstream:
            try:
                ipaddress.IPv4Address(upstream)
            except ValueError as e:
                raise ConfigError("SmartDNS domestic IP upstreams must be IPv4") from e

    return {
        **dns,
        "listen": listen,
        "domestic_domain_set": domain_set,
        "cache_file": cache_file,
        "cache_size": cache_size,
        "bootstrap_servers": bootstrap,
        "speed_ports": ports,
    }


def render_smartdns_profile(profile):
    """Return a newline-terminated SmartDNS configuration."""
    listen = profile["listen"]
    lines = [
        "# Generated by net-auto-switch dns render --engine smartdns",
        f"bind {listen}",
        f"bind-tcp {listen}",
        f"cache-size {profile['cache_size']}",
        "cache-persist yes",
        f"cache-file {profile['cache_file']}",
        "speed-check-mode " + ",".join(f"tcp:{port}" for port in profile["speed_ports"]),
        "response-mode fastest-ip",
        "max-reply-ip-num 1",
    ]
    lines.extend(
        f"server {server} -bootstrap-dns -exclude-default-group"
        for server in profile["bootstrap_servers"]
    )
    lines.extend(f"server-https {upstream}" for upstream in profile["global_upstreams"])
    for upstream in profile["domestic_upstreams"]:
        directive = "server-https" if upstream.startswith("https://") else "server"
        lines.append(f"{directive} {upstream} -group domestic -exclude-default-group")
    lines.extend(
        [
            f"domain-set -name cn -type list -file {profile['domestic_domain_set']}",
            "nameserver /domain-set:cn/domestic",
        ]
    )
    lines.extend(f"nameserver /{domain.lower()}/domestic" for domain in profile["video_domains"])
    return "\n".join(lines) + "\n"
